language: csharp
mono: none
dotnet: 2.0.0
script:
  - dotnet restore  ./src/DotNetRelease
  - dotnet restore  ./src/DotNetRelease.Console
  - dotnet restore  ./src/DotNetRelease.Tests
  - dotnet build    ./src/DotNetRelease
  - dotnet build    ./src/DotNetRelease.Console
  - dotnet build    ./src/DotNetRelease.Tests
  - dotnet test     ./src/DotNetRelease.Tests